#!/bin/sh

. /etc/openwrt_release

case "$DISTRIB_TARGET" in
  x86/*) ;;
  *) exit 0 ;;
esac

if [ ! -e /etc/rootpt-resize ] \
&& type parted > /dev/null \
&& lock -n /var/lock/root-resize
then
    logger -t growroot "Expanding root partition..."

    ROOT_BLK="$(readlink -f /sys/dev/block/"$(awk '$9=="/dev/root"{print $3}' /proc/self/mountinfo)")"
    ROOT_DISK="/dev/$(basename "${ROOT_BLK%/*}")"
    ROOT_PART="${ROOT_BLK##*[^0-9]}"

    parted -f -s "${ROOT_DISK}" resizepart "${ROOT_PART}" 100%

    mount_root done
    touch /etc/rootpt-resize

    if [ -e /boot/cmdline.txt ]; then
        NEW_UUID=$(blkid ${ROOT_DISK}p${ROOT_PART} | sed -n 's/.*PARTUUID="\([^"]*\)".*/\1/p')
        sed -i "s/PARTUUID=[^ ]*/PARTUUID=${NEW_UUID}/" /boot/cmdline.txt
    fi

    logger -t growroot "Partition expansion done, rebooting..."
    reboot
fi

exit 1
